title: GSO Step-by-Step Guide
description: A beginner-friendly guide to Generative Search Optimization
theme: just-the-docs
baseurl: "/gso-guide"
url: "https://virtualmase.github.io"
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: UA-XXXXX-X # Replace with your GA ID or remove
